In [1]:
import pandas as pd

In [9]:
data = {"name":["a","b","c","d","a","c"],"eng":[8,7,5,8,8,5],"hindi":[2,3,4,5,2,6]}

In [16]:
df = pd.DataFrame(data)
df

  name  eng  hindi
0    a    8      2
1    b    7      3
2    c    5      4
3    d    8      5
4    a    8      2
5    c    5      6

In [14]:
#df["duplicated"] = df.duplicated()

In [13]:
#df

In [17]:
df.drop_duplicates(keep = "first")

  name  eng  hindi
0    a    8      2
1    b    7      3
2    c    5      4
3    d    8      5
5    c    5      6

In [18]:
df.drop_duplicates(inplace = True)

In [19]:
df

  name  eng  hindi
0    a    8      2
1    b    7      3
2    c    5      4
3    d    8      5
5    c    5      6

In [20]:
dataset  =pd.read_csv("loan_data.csv")
dataset.head(5)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
1,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
2,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
3,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
4,LP001013,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,Urban,Y

In [21]:
dataset.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
376    False
377    False
378    False
379    False
380    False
Length: 381, dtype: bool

In [22]:
dataset.shape

(381, 13)

In [23]:
dataset.drop_duplicates(inplace = True)

In [24]:
dataset.shape

(381, 13)